- name: Neo4j
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
  vars_prompt:
    - name: 'neo4j_selection'
      prompt: "\nPlease choose the number for Neo4j version [ 1/2/3/4/5/6] \n\n
      1: Neo4j 3.4\n
      2: Neo4j 3.5\n
      3: Neo4j 4.0\n
      4: Neo4j 4.1\n
      5: Neo4j 4.3\n
      6: Neo4j latest\n"
      private: no
      default: 4

      
  vars:
    neo4j_select:
      '1': '3.4'
      '2': '3.5'
      '3': '4.0'
      '4': '4.1'
      '5': '4.3'
      '6': 'latest'
    neo4j_version: "{{neo4j_select[neo4j_selection]}}" 
  
  pre_tasks:
   - set_fact:
       jdk_version: "8" 
     when: neo4j_version == "3.4"
   
   - debug:
       msg: neo4j version is {{neo4j_version}}, jdk version is {{jdk_version}}

  roles:
    - { role: role_common, tags: "role_common"}  
    - { role: role_cloud, tags: "role_cloud"} 
    - { role: role_jdk, tags: "role_jdk"}
    - { role: role_nginx, tags: "role_nginx"}
    - { role: role_neo4j, tags: "role_neo4j"}
    - { role: role_init, tags: "role_init"}
    - { role: role_preend, tags: "role_preend"}
    - { role: role_end, tags: "role_end"}
